### PR TITLE
chore(docker): add docker-compose plan and related scripts

### PR DESCRIPTION
**Pull request by actionless**

### CODE REVIEW

**Comment by vied12** [comment]
Is there any way to remove every docker files from `server/` and `client/` and keep them only in `docker/` ?
In other words, having everything what is docker related in `docker/` ?

**Comment by actionless** [comment]
No. On build docker client sends to docker daemon build context. Build context is a whole content of a directory where Dockerfile is stored.

**Comment by nistormihai** [comment]
Looks goo I think

**Comment by actionless** [comment]
squashed

**Comment by vied12** [comment]
Reopened in #28

**Pull request closed without merging**
