### PR TITLE
LBSD-495 Invite users to colaborate

### PR DESCRIPTION
**Pull request by ancafarcas**

### CODE REVIEW

**Comment by ioanpocol** [comment]
:+1: (except the fail of tests, probably a build/library issue)

**Comment by plamut** [comment]
Try to close and reopen the PR to re-run the build, it might help.

**Comment by ancafarcas** [comment]
I will try that and also I'll try a re-base from master if it will not work

**Comment by plamut** [comment]
Seems like rebase is necessary in any case, as there are conflicts. :)

**Pull request closed without merging**
